
INCLUDE += -Imynewt-nimble/nimble/include -Imynewt-nimble/nimble/host/include -Imynewt-nimble/porting/nimble/include/ -Imynewt-nimble/nimble/host/util/include/
INCLUDE += -Imynewt-nimble/nimble/host/store/config/include/ -Imynewt-nimble/nimble/host/store/ram/include/
INCLUDE += -Imynewt-nimble/nimble/host/services/gap/include/ -Imynewt-nimble/nimble/host/services/gatt/include/
#INCLUDE += -Imynewt-nimble/nimble/host/services/ans/include/ -Imynewt-nimble/nimble/host/services/bas/include/
#INCLUDE += -Imynewt-nimble/nimble/host/services/bleuart/include/ -Imynewt-nimble/nimble/host/services/dis/include/
#INCLUDE += -Imynewt-nimble/nimble/host/services/ias/include/ -Imynewt-nimble/nimble/host/services/lls/include/
#INCLUDE += -Imynewt-nimble/nimble/host/services/tps/include/

# find ../mynewt-nimble/nimble/host/ -name *.c | grep -v mesh | grep -v test | xargs -I{} echo SOURCES += {}
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_flow.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_log.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_att_svr.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_atomic.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_store.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_hci_cmd.c
#not useful and errors anyway  SOURCES += ../mynewt-nimble/nimble/host/src/ble_gatts_lcl.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_sm_cmd.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_l2cap.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_att_clt.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_sm_lgcy.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_sm_sc.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_hci.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_adv.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_hci_util.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_stop.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_hci_evt.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_startup.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_dbg.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_eddystone.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_monitor.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_l2cap_sig_cmd.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_store_util.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_misc.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_gap.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_sm.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_conn.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_pvcy.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_mqueue.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_shutdown.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_sm_alg.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_gattc.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_uuid.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_id.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_ibeacon.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_gatts.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_l2cap_sig.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_att.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_cfg.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_l2cap_coc.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_hs_mbuf.c
SOURCES += ../mynewt-nimble/nimble/host/src/ble_att_cmd.c
SOURCES += ../mynewt-nimble/nimble/host/util/src/addr.c
SOURCES += ../mynewt-nimble/nimble/host/store/ram/src/ble_store_ram.c
#not useful and errors anyway  SOURCES += ../mynewt-nimble/nimble/host/store/config/src/ble_store_config.c
#not useful and errors anyway  SOURCES += ../mynewt-nimble/nimble/host/store/config/src/ble_store_config_conf.c
SOURCES += ../mynewt-nimble/nimble/host/services/gatt/src/ble_svc_gatt.c
SOURCES += ../mynewt-nimble/nimble/host/services/gap/src/ble_svc_gap.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/ans/src/ble_svc_ans.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/tps/src/ble_svc_tps.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/bas/src/ble_svc_bas.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/ias/src/ble_svc_ias.c
#already copied into bluetooth.cpp   SOURCES += ../mynewt-nimble/nimble/host/services/bleuart/src/bleuart.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/dis/src/ble_svc_dis.c
#not useful SOURCES += ../mynewt-nimble/nimble/host/services/lls/src/ble_svc_lls.c

SOURCES += ../mynewt-nimble/porting/nimble/src/os_mempool.c
SOURCES += ../mynewt-nimble/porting/nimble/src/os_msys_init.c
SOURCES += ../mynewt-nimble/porting/nimble/src/os_mbuf.c
SOURCES += ../mynewt-nimble/porting/nimble/src/endian.c
SOURCES += ../mynewt-nimble/porting/nimble/src/mem.c
#SOURCES += ../mynewt-nimble/porting/nimble/src/hal_timer.c
#SOURCES += ../mynewt-nimble/porting/nimble/src/nimble_port.c
#SOURCES += ../mynewt-nimble/porting/nimble/src/os_cputime_pwr2.c
#SOURCES += ../mynewt-nimble/porting/nimble/src/os_cputime.c


INCLUDE += -Isrc/nimble
SOURCES += ../mynewt-nimble/apps/blecent/src/peer.c
SOURCES += nimble/nimble_hci.cpp
SOURCES += nimble/nimble_npl_os.cpp
